name: Request Copilot Review
permissions:
  pull-requests: write
  contents: read
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request Copilot Review
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ["github-copilot[bot]"]
            })
